services:
  db:
    image: postgres:15-alpine
    container_name: flyrank_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasksdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: flyrank_fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/tasksdb
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: